services:
    weglot_translate.console.cache_clear:
        class: Weglot\TranslateBundle\Command\CacheClearCommand
        public: true
        arguments: ['@service_container']
        tags:
            - { name: console.command, command: weglot:cache:clear}