services:
    weglot_translate.service.client:
        class: Weglot\TranslateBundle\Services\Client
        arguments: ['%weglot.api_key%']

    weglot_translate.service.parser:
        class: Weglot\TranslateBundle\Services\Parser
        arguments: ['@weglot_translate.service.client', '%weglot.exclude_blocks%']

    weglot_translate.listener.request:
        class: Weglot\TranslateBundle\Listener\RequestListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: ['@weglot_translate.service.parser', '%weglot.destination_languages%']

    weglot_translate.extension.weglot_button:
        class: Weglot\TranslateBundle\Twig\WeglotButtonExtension
        tags:
            - { name: twig.extension }
        calls :
            - [setOriginalLanguage, ['%weglot.original_language%']]
            - [setDestinationLanguages, ['%weglot.destination_languages%']]

    weglot_translate.routing.loader:
      class: Weglot\TranslateBundle\Routing\Loader
      public: false
      arguments:
        - '@weglot_translate.routing.loader.inner'
        - '%weglot.destination_languages%'
        - '%weglot.original_language%'
      decorates: routing.loader

    weglot_translate.routing.router:
      class: Weglot\TranslateBundle\Routing\Router
      public: false
      parent: router.default
      calls:
        - [setDefaultLocale, ['%weglot.original_language%']]
        - [setRequestStack, ['@request_stack']]