services:
    weglot_translate.library.client:
        class: Weglot\Client\Client
        arguments: ['%weglot.api_key%']

    weglot_translate.library.config_provider:
        class: Weglot\Parser\ConfigProvider\ServerConfigProvider

    weglot_translate.service.parser:
        class: Weglot\Parser\Parser
        arguments: ['@weglot_translate.service.client', '@weglot_translate.library.config_provider', '%weglot.exclude_blocks%']

    weglot_translate.service.languages_endpoint:
        class: Weglot\Client\Endpoint\Languages
        arguments: ['@weglot_translate.service.client']

    weglot_translate.listener.request:
        class: Weglot\TranslateBundle\Listener\RequestListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: ['@weglot_translate.service.parser', '%weglot.destination_languages%']

    weglot_translate.extension.weglot_button:
        class: Weglot\TranslateBundle\Twig\WeglotButtonExtension
        tags:
            - { name: twig.extension }
        arguments: ['%weglot.original_language%', '%weglot.destination_languages%', '@weglot_translate.service.languages_endpoint']

    weglot_translate.extension.language_code:
        class: Weglot\TranslateBundle\Twig\LanguageCodeExtension
        tags:
            - { name: twig.extension }
        arguments: ['@weglot_translate.service.languages_endpoint']

    weglot_translate.routing.loader:
      class: Weglot\TranslateBundle\Routing\Loader
      public: false
      arguments:
        - '@weglot_translate.routing.loader.inner'
        - '%weglot.destination_languages%'
        - '%weglot.original_language%'
      decorates: routing.loader

    weglot_translate.routing.router:
      class: Weglot\TranslateBundle\Routing\Router
      public: false
      parent: router.default
      calls:
        - [setDefaultLocale, ['%weglot.original_language%']]
        - [setRequestStack, ['@request_stack']]